# Generated by Django 5.2.1 on 2025-06-07 23:30

import django.db.models.deletion
import storages.backends.s3
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='class_year',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='resume',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='resumes/'),
        ),
        migrations.CreateModel(
            name='EmailCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
