# Generated by Django 5.2.1 on 2025-06-09 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_portfolio_class_year_alter_portfolio_resume_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='goals',
            new_name='research_interests',
        ),
    ]
