# Generated by Django 5.2.1 on 2025-06-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_goals_portfolio_research_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
