# Generated by Django 5.2.1 on 2025-06-29 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile_delete_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentEmailEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('event_type', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('smtp_id', models.CharField(blank=True, max_length=255)),
                ('user_agent', models.TextField(blank=True)),
                ('response', models.TextField(blank=True)),
                ('custom_args', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
