# Generated by Django 5.2.1 on 2025-07-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sentemailrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tos_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
