# Generated by Django 5.2.1 on 2025-07-25 02:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_previewedprofessor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PreviewedProfessor',
            new_name='ViewedProfessorLog',
        ),
        migrations.AlterUniqueTogether(
            name='viewedprofessorlog',
            unique_together=set(),
        ),
    ]
