# Generated by Django 5.2.1 on 2025-07-25 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_previewedprofessor_viewedprofessorlog_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ViewedProfessorLog',
        ),
    ]
