#Form Choices
MAJOR_CHOICES = [
    ('', 'Select Major'),  # Placeholder
    ('Accounting', 'Accounting'), ('Aerospace Engineering', 'Aerospace Engineering'),
    ('Agricultural Business and Management', 'Agricultural Business and Management'),
    ('Agricultural Economics', 'Agricultural Economics'), ('Agricultural Education', 'Agricultural Education'),
    ('Agricultural Journalism', 'Agricultural Journalism'), ('Agricultural Mechanization', 'Agricultural Mechanization'),
    ('Agriculture', 'Agriculture'), ('American History', 'American History'), ('American Literature', 'American Literature'),
    ('American Studies', 'American Studies'), ('Animal Science', 'Animal Science'), ('Anthropology', 'Anthropology'),
    ('Applied Mathematics', 'Applied Mathematics'), ('Aquatic Biology', 'Aquatic Biology'), ('Archaeology', 'Archaeology'),
    ('Architectural Engineering', 'Architectural Engineering'), ('Architecture', 'Architecture'), ('Art', 'Art'),
    ('Art Education', 'Art Education'), ('Art History', 'Art History'), ('Art Therapy', 'Art Therapy'), ('Astronomy', 'Astronomy'),
    ('Atmospheric Science', 'Atmospheric Science'), ('Aviation', 'Aviation'), ('Baking Science', 'Baking Science'),
    ('Biochemistry', 'Biochemistry'), ('Bioethics', 'Bioethics'), ('Biology', 'Biology'), ('Biomedical Engineering', 'Biomedical Engineering'),
    ('Biophysics', 'Biophysics'), ('Botany', 'Botany'), ('Business Administration', 'Business Administration'),
    ('Business Communications', 'Business Communications'), ('Business Education', 'Business Education'), ('Ceramic Engineering', 'Ceramic Engineering'),
    ('Ceramics', 'Ceramics'), ('Chemical Engineering', 'Chemical Engineering'), ('Chemical Physics', 'Chemical Physics'),
    ('Chemistry', 'Chemistry'), ('Child Development', 'Child Development'), ('Child Care', 'Child Care'),
    ('Civil Engineering', 'Civil Engineering'), ('Cognitive Psychology', 'Cognitive Psychology'), ('Comparative Literature', 'Comparative Literature'),
    ('Computer and Information Science', 'Computer and Information Science'), ('Computer Engineering', 'Computer Engineering'),
    ('Computer Graphics', 'Computer Graphics'), ('Computer Science', 'Computer Science'), ('Computer Systems Analysis', 'Computer Systems Analysis'),
    ('Construction Management', 'Construction Management'), ('Creative Writing', 'Creative Writing'), ('Criminal Justice', 'Criminal Justice'),
    ('Criminology', 'Criminology'), ('Culinary Arts', 'Culinary Arts'), ('Dental Hygiene', 'Dental Hygiene'),
    ('Developmental Psychology', 'Developmental Psychology'), ('Diagnostic Medical Sonography', 'Diagnostic Medical Sonography'),
    ('Dietetics', 'Dietetics'), ('Digital Communications', 'Digital Communications'), ('Early Childhood Education', 'Early Childhood Education'),
    ('Economics', 'Economics'), ('Education', 'Education'), ('Educational Psychology', 'Educational Psychology'),
    ('Electrical Engineering', 'Electrical Engineering'), ('Engineering Mechanics', 'Engineering Mechanics'),
    ('Engineering Physics', 'Engineering Physics'), ('English Composition', 'English Composition'),
    ('English Literature', 'English Literature'), ('Entrepreneurship', 'Entrepreneurship'), ('Environmental Science', 'Environmental Science'),
    ('Epidemiology', 'Epidemiology'), ('Ethnic Studies', 'Ethnic Studies'), ('Experimental Psychology', 'Experimental Psychology'),
    ('Finance', 'Finance'), ('Food Science', 'Food Science'), ('Forensic Science', 'Forensic Science'), ('French', 'French'),
    ('Game Design', 'Game Design'), ('Genetics', 'Genetics'), ('Geography', 'Geography'), ('Geology', 'Geology'),
    ('Geophysics', 'Geophysics'), ('German', 'German'), ('Graphic Design', 'Graphic Design'), ('Health Administration', 'Health Administration'),
    ('Hebrew', 'Hebrew'), ('Historic Preservation', 'Historic Preservation'), ('History', 'History'),
    ('Home Economics', 'Home Economics'), ('Hospitality', 'Hospitality'), ('Human Communications', 'Human Communications'),
    ('Human Development', 'Human Development'), ('Industrial Design', 'Industrial Design'), ('Industrial Engineering', 'Industrial Engineering'),
    ('Industrial Management', 'Industrial Management'), ('Information Technology', 'Information Technology'),
    ('International Business', 'International Business'), ('International Relations', 'International Relations'),
    ('Italian', 'Italian'), ('Japanese', 'Japanese'), ('Jewish Studies', 'Jewish Studies'), ('Kinesiology', 'Kinesiology'),
    ('Latin American Studies', 'Latin American Studies'), ('Linguistics', 'Linguistics'), ('Management Information Systems', 'Management Information Systems'),
    ('Marketing', 'Marketing'), ('Mathematics', 'Mathematics'), ('Mechanical Engineering', 'Mechanical Engineering'),
    ('Medical Technology', 'Medical Technology'), ('Medieval and Renaissance Studies', 'Medieval and Renaissance Studies'),
    ('Microbiology', 'Microbiology'), ('Middle Eastern Studies', 'Middle Eastern Studies'), ('Military Science', 'Military Science'),
    ('Molecular Biology', 'Molecular Biology'), ('Molecular Genetics', 'Molecular Genetics'), ('Mortuary Science', 'Mortuary Science'),
    ('Music', 'Music'), ('Music Composition', 'Music Composition'), ('Music Education', 'Music Education'),
    ('Music History', 'Music History'), ('Music Performance', 'Music Performance'), ('Music Therapy', 'Music Therapy'),
    ('Native American Studies', 'Native American Studies'), ('Naval Architecture', 'Naval Architecture'),
    ('Neurobiology', 'Neurobiology'), ('Neuroscience', 'Neuroscience'), ('Nuclear Engineering', 'Nuclear Engineering'),
    ('Nursing', 'Nursing'), ('Nutrition', 'Nutrition'), ('Occupational Therapy', 'Occupational Therapy'),
    ('Oceanography', 'Oceanography'), ('Optometry', 'Optometry'), ('Organizational Behavior Studies', 'Organizational Behavior Studies'),
    ('Painting', 'Painting'), ('Paleontology', 'Paleontology'), ('Pastoral Studies', 'Pastoral Studies'),
    ('Petroleum Engineering', 'Petroleum Engineering'), ('Pharmacology', 'Pharmacology'), ('Pharmacy', 'Pharmacy'),
    ('Philosophy', 'Philosophy'), ('Photography', 'Photography'), ('Physical Education', 'Physical Education'),
    ('Physical Therapy', 'Physical Therapy'), ('Physics', 'Physics'), ('Physiology', 'Physiology'),
    ('Physiological Psychology', 'Physiological Psychology'), ('Planetary Science', 'Planetary Science'),
    ('Plant Pathology', 'Plant Pathology'), ('Plant Sciences', 'Plant Sciences'), ('Political Science', 'Political Science'),
    ('Portuguese', 'Portuguese'), ('Pre-Dentistry', 'Pre-Dentistry'), ('Pre-Law', 'Pre-Law'), ('Pre-Medicine', 'Pre-Medicine'),
    ('Pre-Optometry', 'Pre-Optometry'), ('Pre-Seminary', 'Pre-Seminary'), ('Pre-Veterinary', 'Pre-Veterinary'),
    ('Printmaking', 'Printmaking'), ('Product Design', 'Product Design'), ('Psychology', 'Psychology'),
    ('Public Administration', 'Public Administration'), ('Public Health', 'Public Health'), ('Public Policy Analysis', 'Public Policy Analysis'),
    ('Radiologic Technology', 'Radiologic Technology'), ('Radio and Television', 'Radio and Television'),
    ('Rehabilitation Services', 'Rehabilitation Services'), ('Religious Studies', 'Religious Studies'),
    ('Retailing', 'Retailing'), ('Russian', 'Russian'), ('Scandinavian Studies', 'Scandinavian Studies'),
    ('Slavic Languages and Literatures', 'Slavic Languages and Literatures'), ('Social Psychology', 'Social Psychology'),
    ('Social Work', 'Social Work'), ('Sociology', 'Sociology'), ('Soil Science', 'Soil Science'), ('South Asian Studies', 'South Asian Studies'),
    ('Spanish', 'Spanish'), ('Special Education', 'Special Education'), ('Speech Pathology', 'Speech Pathology'),
    ('Sports Management', 'Sports Management'), ('Statistics', 'Statistics'), ('Sustainable Resource Management', 'Sustainable Resource Management'),
    ('Theater', 'Theater'), ('Theology', 'Theology'), ('Toxicology', 'Toxicology'), ('Urban Planning', 'Urban Planning'),
    ('Urban Studies', 'Urban Studies'), ('Visual Communication', 'Visual Communication'), ('Visual Design', 'Visual Design'),
    ('Web Design', 'Web Design'), ('Web Management', 'Web Management'), ('Women\'s Studies', 'Women\'s Studies'),
    ('Zoology', 'Zoology'),
]

CLASS_YEAR_CHOICES = [
    ('', 'Select Academic Level'), 
    ('High School Student', 'High School Student'),
    ('Undergraduate Freshman', 'Undergraduate Freshman'),
    ('Undergraduate Sophomore', 'Undergraduate Sophomore'),
    ('Undergraduate Junior', 'Undergraduate Junior'),
    ('Undergraduate Senior', 'Undergraduate Senior'),
    ('Masters Student', 'Masters Student'),
    ('Doctoral Student', 'Doctoral Student'),
    ('Post-Graduate', 'Post-Graduate'),

]

US_UNIVERSITY_CHOICES = [
    ('', 'Select University'),
    ('Harvard University', 'Harvard University'),
    ('Stanford University', 'Stanford University'),
    ('Massachusetts Institute of Technology', 'Massachusetts Institute of Technology'),
    ('University of California, Berkeley', 'University of California, Berkeley'),
    ('California Institute of Technology', 'California Institute of Technology'),
    ('Princeton University', 'Princeton University'),
    ('Yale University', 'Yale University'),
    ('Columbia University', 'Columbia University'),
    ('University of Chicago', 'University of Chicago'),
    ('University of Pennsylvania', 'University of Pennsylvania'),
    ('Johns Hopkins University', 'Johns Hopkins University'),
    ('Duke University', 'Duke University'),
    ('Northwestern University', 'Northwestern University'),
    ('University of Michigan', 'University of Michigan'),
    ('Cornell University', 'Cornell University'),
    ('New York University', 'New York University'),
    ('University of California, Los Angeles', 'University of California, Los Angeles'),
    ('University of Washington', 'University of Washington'),
    ('University of Wisconsin-Madison', 'University of Wisconsin-Madison'),
    ('University of Texas at Austin', 'University of Texas at Austin'),
    ('University of North Carolina at Chapel Hill', 'University of North Carolina at Chapel Hill'),
    ('Carnegie Mellon University', 'Carnegie Mellon University'),
    ('Brown University', 'Brown University'),
    ('Boston University', 'Boston University'),
    ('University of California, San Diego', 'University of California, San Diego'),
    ('University of Illinois at Urbana-Champaign', 'University of Illinois at Urbana-Champaign'),
    ('University of Florida', 'University of Florida'),
    ('University of Southern California', 'University of Southern California'),
    ('Ohio State University', 'Ohio State University'),
    ('Pennsylvania State University', 'Pennsylvania State University'),
    ('A.T. Still University', 'A.T. Still University'),
    ('Abilene Christian University', 'Abilene Christian University'),
    ('Adams State University', 'Adams State University'),
    ('Adelphi University', 'Adelphi University'),
    ('Air Force Institute of Technology', 'Air Force Institute of Technology'),
    ('Alabama A&M University', 'Alabama A&M University'),
    ('Alabama State University', 'Alabama State University'),
    ('Albany State University', 'Albany State University'),
    ('American University', 'American University'),
    ('Amherst College', 'Amherst College'),
    ('Arizona State University', 'Arizona State University'),
    ('Auburn University', 'Auburn University'),
    ('Ball State University', 'Ball State University'),
    ('Baylor University', 'Baylor University'),
    ('Brandeis University', 'Brandeis University'),
    ('Brigham Young University', 'Brigham Young University'),
    ('Bucknell University', 'Bucknell University'),
    ('Case Western Reserve University', 'Case Western Reserve University'),
    ('Clemson University', 'Clemson University'),
    ('Colorado State University', 'Colorado State University'),
    ('Dartmouth College', 'Dartmouth College'),
    ('Emory University', 'Emory University'),
    ('Florida State University', 'Florida State University'),
    ('George Washington University', 'George Washington University'),
    ('Georgetown University', 'Georgetown University'),
    ('Georgia Institute of Technology', 'Georgia Institute of Technology'),
    ('Indiana University Bloomington', 'Indiana University Bloomington'),
    ('Iowa State University', 'Iowa State University'),
    ('Kansas State University', 'Kansas State University'),
    ('Louisiana State University', 'Louisiana State University'),
    ('Michigan State University', 'Michigan State University'),
    ('Mississippi State University', 'Mississippi State University'),
    ('New Mexico State University', 'New Mexico State University'),
    ('North Carolina State University', 'North Carolina State University'),
    ('Oregon State University', 'Oregon State University'),
    ('Purdue University', 'Purdue University'),
    ('Rice University', 'Rice University'),
    ('Rutgers University', 'Rutgers University'),
    ('Southern Methodist University', 'Southern Methodist University'),
    ('Syracuse University', 'Syracuse University'),
    ('Texas A&M University', 'Texas A&M University'),
    ('Tufts University', 'Tufts University'),
    ('Tulane University', 'Tulane University'),
    ('University of Arizona', 'University of Arizona'),
    ('University of Colorado Boulder', 'University of Colorado Boulder'),
    ('University of Georgia', 'University of Georgia'),
    ('University of Iowa', 'University of Iowa'),
    ('University of Kansas', 'University of Kansas'),
    ('University of Kentucky', 'University of Kentucky'),
    ('University of Maryland', 'University of Maryland'),
    ('University of Minnesota', 'University of Minnesota'),
    ('University of Missouri', 'University of Missouri'),
    ('University of Nebraska', 'University of Nebraska'),
    ('University of Notre Dame', 'University of Notre Dame'),
    ('University of Oklahoma', 'University of Oklahoma'),
    ('University of Oregon', 'University of Oregon'),
    ('University of Pittsburgh', 'University of Pittsburgh'),
    ('University of Rochester', 'University of Rochester'),
    ('University of South Carolina', 'University of South Carolina'),
    ('University of Tennessee', 'University of Tennessee'),
    ('University of Utah', 'University of Utah'),
    ('University of Virginia', 'University of Virginia'),
    ('University of Wisconsin', 'University of Wisconsin'),
    ('Vanderbilt University', 'Vanderbilt University'),
    ('Virginia Tech', 'Virginia Tech'),
    ('Wake Forest University', 'Wake Forest University'),
    ('Washington State University', 'Washington State University'),
    ('Washington University in St. Louis', 'Washington University in St. Louis'),
    ('West Virginia University', 'West Virginia University'),
    ('Worcester Polytechnic Institute', 'Worcester Polytechnic Institute'),
]